FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.16

RUN echo "xpack.security.enabled: false" >> /usr/share/elasticsearch/config/elasticsearch.yml \
	&& echo "discovery.type: single-node" >> /usr/share/elasticsearch/config/elasticsearch.yml \
	&& bin/elasticsearch-plugin install -b analysis-icu \
	&& bin/elasticsearch-plugin install -b analysis-phonetic